#!/bin/sh

REVISION=1.0

APPEND=-dist
KERNEL_VER=3.10.39-rk


#######################################################################
##
## Generate RK module packaging script
##
#######################################################################

MKMOD_SH=rk-make-module-pkg.sh
MODDIR=linux-rk-mod-$KERNEL_VER$APPEND"_"$REVISION"_\`date +%b%d-%Y\`"
rm -f $MKMOD_SH
echo "#!/bin/sh" >> $MKMOD_SH
echo "#\n# DO NOT EDIT THIS FILE\n# It is automatically generated by rk-make-kernel-pkg.sh\n#\n" >> $MKMOD_SH
echo "REVISION="$REVISION >> $MKMOD_SH
echo "APPEND="$APPEND >> $MKMOD_SH
echo "KERNEL_VER="$KERNEL_VER >> $MKMOD_SH

echo "\ncd ../" >> $MKMOD_SH
echo "make" >> $MKMOD_SH
echo "rm -rf "$MODDIR >> $MKMOD_SH
echo "mkdir "$MODDIR >> $MKMOD_SH
echo "cp rk.ko $MODDIR/rk_partitioned.ko" >> $MKMOD_SH
echo "make global" >> $MKMOD_SH
echo "cp rk.ko $MODDIR/rk_global.ko" >> $MKMOD_SH
echo "cd "$MODDIR >> $MKMOD_SH
echo "ln -s rk_partitioned.ko rk.ko" >> $MKMOD_SH
#echo "ln -s rk_global.ko rk.ko" >> $MKMOD_SH

echo "mkdir mcrkmod" >> $MKMOD_SH
echo "cp ../*.c mcrkmod" >> $MKMOD_SH
echo "sed 's/KDIR =.*/KDIR = \/usr\/src\/linux-headers-"$KERNEL_VER$APPEND"/' ../Makefile > mcrkmod/Makefile" >> $MKMOD_SH

echo "mkdir mcrkmod/utils" >> $MKMOD_SH
echo "cp ../utils/*.c mcrkmod/utils" >> $MKMOD_SH
echo "sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-"$KERNEL_VER$APPEND"/' ../utils/Makefile > mcrkmod/utils/Makefile" >> $MKMOD_SH

echo "mkdir mcrkmod/utils/mem-reserve" >> $MKMOD_SH
echo "cp ../utils/mem-reserve/*.c mcrkmod/utils/mem-reserve" >> $MKMOD_SH
echo "sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-"$KERNEL_VER$APPEND"/' ../utils/mem-reserve/Makefile > mcrkmod/utils/mem-reserve/Makefile" >> $MKMOD_SH

echo "mkdir mcrkmod/utils/virt" >> $MKMOD_SH
echo "cp ../utils/virt/*.c mcrkmod/utils/virt" >> $MKMOD_SH
echo "sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-"$KERNEL_VER$APPEND"/' ../utils/virt/Makefile > mcrkmod/utils/virt/Makefile" >> $MKMOD_SH

echo "mkdir mcrkmod/tests" >> $MKMOD_SH
echo "mkdir mcrkmod/tests/multicore" >> $MKMOD_SH
echo "cp ../tests/multicore/*.c mcrkmod/tests/multicore" >> $MKMOD_SH
echo "sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-"$KERNEL_VER$APPEND"/' ../tests/multicore/Makefile > mcrkmod/tests/multicore/Makefile" >> $MKMOD_SH

echo "mkdir mcrkmod/tests/rk_mutex" >> $MKMOD_SH
echo "cp ../tests/rk_mutex/*.c mcrkmod/tests/rk_mutex" >> $MKMOD_SH
echo "sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-"$KERNEL_VER$APPEND"/' ../tests/rk_mutex/Makefile > mcrkmod/tests/rk_mutex/Makefile" >> $MKMOD_SH

echo "mkdir mcrkmod/tests/vmpcp_intervm" >> $MKMOD_SH
echo "cp ../tests/vmpcp_intervm/*.c mcrkmod/tests/vmpcp_intervm" >> $MKMOD_SH
echo "sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-"$KERNEL_VER$APPEND"/' ../tests/vmpcp_intervm/Makefile > mcrkmod/tests/vmpcp_intervm/Makefile" >> $MKMOD_SH

#echo "mkdir test-cpursv" >> $MKMOD_SH
#echo "cp ../tests/cpursv/*.c test-cpursv" >> $MKMOD_SH
#echo "sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-"$KERNEL_VER$APPEND"/' ../tests/cpursv/Makefile > test-cpursv/Makefile" >> $MKMOD_SH

echo "cd ../" >> $MKMOD_SH
echo "tar cvfz "$MODDIR".tgz "$MODDIR >> $MKMOD_SH
echo "" >> $MKMOD_SH


#######################################################################
##
## Compile kernel package & Generate KPKG install script
##
#######################################################################
cd ../../
CONCURRENCY_LEVEL=8
fakeroot make-kpkg --initrd --append-to-version=$APPEND --revision=$REVISION kernel-image kernel-headers
cd ../

<<COMMENT1
TARGET=amd64
INSTALL_SH=install-linux-$KERNEL_VER$APPEND"_"$REVISION"_"$TARGET.sh
rm -f $INSTALL_SH
echo "#!/bin/sh" >> $INSTALL_SH
echo "sudo dpkg -i --force-all linux-headers-"$KERNEL_VER$APPEND"_"$REVISION"_"$TARGET".deb" >> $INSTALL_SH
echo "sudo dpkg -i --force-all linux-image-"$KERNEL_VER$APPEND"_"$REVISION"_"$TARGET".deb" >> $INSTALL_SH
echo "sudo ln -s /usr/src/linux-headers-"$KERNEL_VER$APPEND" /lib/modules/"$KERNEL_VER$APPEND"/build" >> $INSTALL_SH
echo "sudo mkinitramfs "$KERNEL_VER$APPEND" -o /boot/initrd.img-"$KERNEL_VER$APPEND >> $INSTALL_SH
echo "sudo update-grub" >> $INSTALL_SH
COMMENT1

