#!/bin/sh
#
# DO NOT EDIT THIS FILE
# It is automatically generated by rk-make-kernel-pkg.sh
#

REVISION=1.0
APPEND=-dist
KERNEL_VER=3.10.39-rk

cd ../
make
rm -rf linux-rk-mod-3.10.39-rk-dist_1.0_`date +%b%d-%Y`
mkdir linux-rk-mod-3.10.39-rk-dist_1.0_`date +%b%d-%Y`
cp rk.ko linux-rk-mod-3.10.39-rk-dist_1.0_`date +%b%d-%Y`/rk_partitioned.ko
make global
cp rk.ko linux-rk-mod-3.10.39-rk-dist_1.0_`date +%b%d-%Y`/rk_global.ko
cd linux-rk-mod-3.10.39-rk-dist_1.0_`date +%b%d-%Y`
ln -s rk_partitioned.ko rk.ko
mkdir mcrkmod
cp ../*.c mcrkmod
sed 's/KDIR =.*/KDIR = \/usr\/src\/linux-headers-3.10.39-rk-dist/' ../Makefile > mcrkmod/Makefile
mkdir mcrkmod/utils
cp ../utils/*.c mcrkmod/utils
sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-3.10.39-rk-dist/' ../utils/Makefile > mcrkmod/utils/Makefile
mkdir mcrkmod/utils/mem-reserve
cp ../utils/mem-reserve/*.c mcrkmod/utils/mem-reserve
sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-3.10.39-rk-dist/' ../utils/mem-reserve/Makefile > mcrkmod/utils/mem-reserve/Makefile
mkdir mcrkmod/utils/virt
cp ../utils/virt/*.c mcrkmod/utils/virt
sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-3.10.39-rk-dist/' ../utils/virt/Makefile > mcrkmod/utils/virt/Makefile
mkdir mcrkmod/tests
mkdir mcrkmod/tests/multicore
cp ../tests/multicore/*.c mcrkmod/tests/multicore
sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-3.10.39-rk-dist/' ../tests/multicore/Makefile > mcrkmod/tests/multicore/Makefile
mkdir mcrkmod/tests/rk_mutex
cp ../tests/rk_mutex/*.c mcrkmod/tests/rk_mutex
sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-3.10.39-rk-dist/' ../tests/rk_mutex/Makefile > mcrkmod/tests/rk_mutex/Makefile
mkdir mcrkmod/tests/vmpcp_intervm
cp ../tests/vmpcp_intervm/*.c mcrkmod/tests/vmpcp_intervm
sed 's/KERNEL_DIR =.*/KERNEL_DIR = \/usr\/src\/linux-headers-3.10.39-rk-dist/' ../tests/vmpcp_intervm/Makefile > mcrkmod/tests/vmpcp_intervm/Makefile
cd ../
tar cvfz linux-rk-mod-3.10.39-rk-dist_1.0_`date +%b%d-%Y`.tgz linux-rk-mod-3.10.39-rk-dist_1.0_`date +%b%d-%Y`

